name: heptools-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - rich
  - numpy
  - scipy
  - pandas
  - matplotlib
  - bokeh
  - graphviz
  - dask-jobqueue
# Scikit-HEP
  - awkward
  - uproot
  - hist
# CMS
  - coffea
  - correctionlib