name: heptools-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rich
  - numpy
  - scipy
  - pandas
  - matplotlib
  - bokeh
  - graphviz
  - dask-jobqueue
  - pip
  - pip:
    - graphviz
# Scikit-HEP
  - awkward
  - uproot
  - hist
# CMS
  - coffea
  - correctionlib