name: heptools-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - rich
  - numpy
  - scipy
  - pandas
  - matplotlib
# Dask jobqueue, dashboard, visualize
  - dask_jobqueue
  - bokeh
  - graphviz
# Scikit-HEP
  - awkward
  - uproot
  - hist
# CMS
  - coffea
  - correctionlib