name: heptools-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pycurl
# numerical
  - numpy
  - scipy
  - pandas
# visualization
  - matplotlib
  - bokeh
  - graphviz
  - pip:
    - graphviz
  - rich
# parallel
  - dask-jobqueue

# Scikit-HEP
  - awkward
  - uproot=4.3.*
  - hist
# CMS
  - coffea=0.7.21
  - correctionlib
  - pip:
    - dbs3-client