[project]
name = "heptools"
version = "0.4.0"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "numpy",
    "matplotlib",
    "dask-jobqueue",
    # Scikit-HEP
    "awkward",
    "uproot",
    "hist",
    # CMS
    "coffea",
    "correctionlib",
]
