[project]
name = "heptools"
version = "0.2.3"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib",
    "dask_jobqueue",
    "rich",
    "awkward",
    "hist",
    "uproot",
    "coffea",
    "correctionlib",
]
