[project]
name = "heptools"
version = "0.2.6"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "numpy",
    "matplotlib",
    "dask-jobqueue",
# Scikit-HEP
    "awkward",
    "uproot",
    "hist",
# CMS
    "coffea",
    "correctionlib",
]
