[project]
name = "heptools"
version = "0.2.3"
requires-python = ">=3.9"
dependencies = [
    "rich",
    "numpy",
    "matplotlib",
    "dask-jobqueue",
# Scikit-HEP
    "awkward",
    "uproot",
    "hist",
# CMS
    "coffea",
    "correctionlib",
]
