name: heptools-exp
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pycurl
  # machine learning
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  # numerical
  - numpy
  - scipy
  - pandas
  - pyarrow
  # visualization
  - matplotlib
  - bokeh
  - graphviz
  - pip:
      - graphviz
  - rich
  # Scikit-HEP
  - uproot
  - awkward
  - awkward-pandas