name: ml
channels:
  - conda-forge
dependencies:
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.11.0
  - scikit-learn
  # GPU
  - cupy
  # monitor
  - gevent
  - gevent-websocket
  - flask
  - flask-socketio
