name: ml
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pycurl
  # numerical
  - numpy
  - scipy
  - pandas
  - pyarrow
  # visualization
  - matplotlib
  - bokeh
  - graphviz
  - pip:
    - graphviz
  - rich
  # Scikit-HEP
  - uproot
  - awkward
  - awkward-pandas
  # machine learning
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - scikit-learn
  # monitor
  - gevent
  - gevent-websocket
  - flask
  - flask-socketio