name: docker-image

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: publish_docker_image_exp
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push experimental
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/experimental/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/heptools:exp
