name: Build and push Docker image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    concurrency:
      group: publish_docker_image_${{ inputs.tag }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/${{ inputs.tag }}/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/heptools:${{ inputs.tag }}
