name: Create release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  release-vscode-extension:
    uses: ./.github/workflows/job-vscode.yml
    with:
      tag: ${{ inputs.tag }}
