name: Create release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  delete-release:
    uses: ./.github/workflows/job-delete-release.yml
    with:
      tag: ${{ inputs.tag }}

  release-vscode-extension:
    needs: delete-release
    uses: ./.github/workflows/job-vscode.yml
    with:
      tag: ${{ inputs.tag }}
