name: Create tag

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    concurrency:
      group: create_tag_${{ inputs.tag }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            const args = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            }

            github.rest.git.createRef({
              ...args,
              ref: 'refs/tags/${{ inputs.tag }}'
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                ...args,
                ref: 'tags/${{ inputs.tag }}'
              });
            })
