name: Build VSCode extension and release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build-vscode-extension:
    runs-on: ubuntu-latest
    concurrency:
      group: build_vscode_extension_${{ inputs.tag }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: LICENSE
