name: Delete release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  delete-release:
    runs-on: ubuntu-latest
    concurrency:
      group: delete_release_${{ inputs.tag }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete release
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: releases } = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: "${{ inputs.tag }}"
              });
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: releases.id
              });
            } catch (error) {}
