name: Build Docker image with heptools

on:
  push:
    branches:
      - master
    paths:
      - "docker/latest.*"
      - "heptools/**"
      - "setup.cfg"
      - "pyproject.toml"

jobs:
  docker-image-latest:
    uses: ./.github/workflows/job-docker.yml
    with:
      tag: latest
    secrets: inherit
