name: Default workflows for master branch

on:
  push:
    branches:
      - "master"

jobs:
  docker-image-latest:
    uses: ./.github/workflows/job-docker.yml
    with:
      tag: latest
    secrets: inherit
  docker-image-exp:
    uses: ./.github/workflows/job-docker.yml
    with:
      tag: exp
    secrets: inherit
  docs:
    permissions:
      contents: write
    uses: ./.github/workflows/job-sphinx.yml
