name: Build Docker image for machine learning with GPU

on:
  push:
    branches:
      - master
    paths:
      - "docker/ml-gpu.*"

jobs:
  docker-image-ml:
    uses: ./.github/workflows/job-docker.yml
    with:
      tag: ml-gpu
    secrets: inherit
