name: Build Docker image for machine learning

on:
  push:
    branches:
      - master
    paths:
      - "docker/ml-cpu.*"

jobs:
  docker-image-ml:
    uses: ./.github/workflows/job-docker.yml
    with:
      tag: ml-cpu
    secrets: inherit
