name: Create nightly release

on:
  push:
    branches:
      - master
    paths:
      - "vscode-extension/**"
jobs:
  create-tag-nightly:
    permissions:
      contents: write
    uses: ./.github/workflows/job-create-tag.yml
    with:
      tag: nightly

  release-nightly:
    needs: create-tag-nightly
    permissions:
      contents: write
    uses: ./.github/workflows/job-release.yml
    with:
      tag: nightly
