name: Build Docker image for machine learning with CUDA

on:
  push:
    branches:
      - master
    paths:
      - "docker/ml-cuda.*"

jobs:
  docker-image-ml:
    strategy:
      matrix:
        cuda-version: ["13.1"]
    uses: ./.github/workflows/job-docker.yml
    with:
      file: ml-cuda
      tag: ml-cuda-${{ matrix.cuda-version }}
      args: CUDA_VERSION=${{ matrix.cuda-version }}
    secrets: inherit
