name: Build Docker image for machine learning

on:
  push:
    branches:
      - "master"
    paths:
      - "docker/ml.Dockerfile"
      - "docker/ml.env.yml"

jobs:
  docker-image-ml:
    uses: ./.github/workflows/job-docker.yml
    with:
      tag: ml
    secrets: inherit
